// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: HelloService.proto

package es.jorgesanz.grpcservice.prototype;

public final class HelloServiceOuterClass {
  private HelloServiceOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_es_jorgesanz_grpcservice_prototype_HelloRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_es_jorgesanz_grpcservice_prototype_HelloRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_es_jorgesanz_grpcservice_prototype_HelloResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_es_jorgesanz_grpcservice_prototype_HelloResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022HelloService.proto\022\"es.jorgesanz.grpcs" +
      "ervice.prototype\"3\n\014HelloRequest\022\021\n\tfirs" +
      "tName\030\001 \001(\t\022\020\n\010lastName\030\002 \001(\t\"!\n\rHelloRe" +
      "sponse\022\020\n\010greeting\030\001 \001(\t2|\n\014HelloService" +
      "\022l\n\005hello\0220.es.jorgesanz.grpcservice.pro" +
      "totype.HelloRequest\0321.es.jorgesanz.grpcs" +
      "ervice.prototype.HelloResponseB\002P\001b\006prot" +
      "o3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_es_jorgesanz_grpcservice_prototype_HelloRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_es_jorgesanz_grpcservice_prototype_HelloRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_es_jorgesanz_grpcservice_prototype_HelloRequest_descriptor,
        new java.lang.String[] { "FirstName", "LastName", });
    internal_static_es_jorgesanz_grpcservice_prototype_HelloResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_es_jorgesanz_grpcservice_prototype_HelloResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_es_jorgesanz_grpcservice_prototype_HelloResponse_descriptor,
        new java.lang.String[] { "Greeting", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
